# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.1
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods
script:
  - pod lib lint
